feat: demox

diff --git a/.github/workflows/build-scan.yml b/.github/workflows/build-scan.yml
--- a/.github/workflows/build-scan.yml
+++ b/.github/workflows/build-scan.yml
@@ -1,65 +1,78 @@
 name: .NET build and scan
 
 on:
-  push:
-    branches:
-      - develop
-
-run-name: "🔧 build, test & scan on ${{ github.ref_name }}"
+  workflow_dispatch:
 
 jobs:
-  build-and-analyze:
+  sonarqube:
     runs-on: ubuntu-latest
     steps:
-      - name: 🔍 Check secrets are defined
-        run: |
-          [[ -z "${{ secrets.SONAR_PROJECT_KEY }}" ]] && echo "SONAR_PROJECT_KEY is EMPTY" && exit 1
-          [[ -z "${{ secrets.SONAR_HOST_URL }}" ]] && echo "SONAR_HOST_URL is EMPTY" && exit 1
-          [[ -z "${{ secrets.SONAR_TOKEN }}" ]] && echo "SONAR_TOKEN is EMPTY" && exit 1
-          echo "✅ All required secrets are present"
-
-      - name: Checkout code
-        uses: actions/checkout@v4
+      - uses: actions/checkout@v4
         with:
-          fetch-depth: 0 # needed for Sonar
+          fetch-depth: 0
 
-      - name: Setup .NET SDK
-        uses: actions/setup-dotnet@v4
+      - name: SonarScanner
+        uses: highbyte/sonarscan-dotnet@v2.4.2
         with:
-          dotnet-version: "9.0.x" # adjust to your version
+          sonarProjectKey: ${{ secrets.SONAR_PROJECT_KEY }}
+          sonarProjectName: "SampleAspireSolution"
+          sonarHostname: "https://sonarqube.dev.qlogistical.com/"
+    env:
+      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Cache SonarQube packages
-        uses: actions/cache@v4
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
+  # build-and-analyze:
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: 🔍 Check secrets are defined
+  #       run: |
+  #         [[ -z "${{ secrets.SONAR_PROJECT_KEY }}" ]] && echo "SONAR_PROJECT_KEY is EMPTY" && exit 1
+  #         [[ -z "${{ secrets.SONAR_HOST_URL }}" ]] && echo "SONAR_HOST_URL is EMPTY" && exit 1
+  #         [[ -z "${{ secrets.SONAR_TOKEN }}" ]] && echo "SONAR_TOKEN is EMPTY" && exit 1
+  #         echo "✅ All required secrets are present"
 
-      - name: Cache SonarScanner .NET tool
-        id: cache-sonar-scanner
-        uses: actions/cache@v4
-        with:
-          path: .sonarscanner/tools
-          key: ${{ runner.os }}-sonar-scanner
-          restore-keys: ${{ runner.os }}-sonar-scanner
+  #     - name: Checkout code
+  #       uses: actions/checkout@v4
+  #       with:
+  #         fetch-depth: 0 # needed for Sonar
 
-      - name: Install SonarScanner .NET tool
-        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
-        run: dotnet tool install dotnet-sonarscanner --tool-path ./.sonarscanner/tools
+  #     - name: Setup .NET SDK
+  #       uses: actions/setup-dotnet@v4
+  #       with:
+  #         dotnet-version: "9.0.x" # adjust to your version
 
-      - name: SonarQube Begin Analysis
-        run: |
-          ./.sonarscanner/tools/dotnet-sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /d:sonar.host.url="https://sonarqube.dev.qlogistical.com/" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+  #     - name: Cache SonarQube packages
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: ~/.sonar/cache
+  #         key: ${{ runner.os }}-sonar
+  #         restore-keys: ${{ runner.os }}-sonar
 
-      - name: Restore dependencies
-        run: dotnet restore
+  #     - name: Cache SonarScanner .NET tool
+  #       id: cache-sonar-scanner
+  #       uses: actions/cache@v4
+  #       with:
+  #         path: .sonarscanner/tools
+  #         key: ${{ runner.os }}-sonar-scanner
+  #         restore-keys: ${{ runner.os }}-sonar-scanner
 
-      - name: Build
-        run: dotnet build --no-restore --configuration Release
+  #     - name: Install SonarScanner .NET tool
+  #       if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+  #       run: dotnet tool install dotnet-sonarscanner --tool-path ./.sonarscanner/tools
 
-      - name: Run tests
-        run: dotnet test --no-build --configuration Release --verbosity normal
+  #     - name: SonarQube Begin Analysis
+  #       run: |
+  #         ./.sonarscanner/tools/dotnet-sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" /d:sonar.host.url="https://sonarqube.dev.qlogistical.com/" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
 
-      - name: SonarQube End Analysis
-        run: |
-          ./.sonarscanner/tools/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+  #     - name: Restore dependencies
+  #       run: dotnet restore
+
+  #     - name: Build
+  #       run: dotnet build --no-restore --configuration Release
+
+  #     - name: Run tests
+  #       run: dotnet test --no-build --configuration Release --verbosity normal
+
+  #     - name: SonarQube End Analysis
+  #       run: |
+  #         ./.sonarscanner/tools/dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
